import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1440, height: 980 }, deviceScaleFactor: 2 })).newPage();
await p.goto('http://localhost:3210/');
await p.waitForTimeout(400);
await p.screenshot({ path: '/tmp/b-prompt.png', clip: { x: 0, y: 0, width: 1440, height: 700 } });
await p.locator('#gen-example').click();
await p.locator('#run').click();
await p.locator('#questions-panel').waitFor({ state: 'visible', timeout: 20000 });
await p.screenshot({ path: '/tmp/b-questions.png', clip: { x: 0, y: 0, width: 1440, height: 760 } });
await p.locator('#q-skip-all').click();
await p.locator('#health-row').waitFor({ state: 'visible', timeout: 30000 });
await p.waitForTimeout(1400);
await p.screenshot({ path: '/tmp/b-overview.png', clip: { x: 0, y: 0, width: 1440, height: 980 } });
await p.locator('.nav-item[data-page=schedule]').click();
await p.waitForTimeout(700);
await p.screenshot({ path: '/tmp/b-timeline-mid.png', clip: { x: 0, y: 0, width: 1440, height: 980 } });
await p.waitForTimeout(1600);
await p.screenshot({ path: '/tmp/b-timeline.png', clip: { x: 0, y: 0, width: 1440, height: 980 } });
await b.close();
